### ISSUE TITLE
Cannot write to telegraf

### ISSUE THREAD

**Issue by macr023** [tkurki/signalk-to-influxdb#67]
I could of made a mistake on my end, but after losing my SD card on my pi running openplotter, I reinstalled to the latest version. I can use signalk-to-influxdb to write directly to my influxdb instances, however I had telegraf used to buffer the data. I am getting these errors now, I tried downgrading influx and telegraf with no avail. 

Error:
May 02 21:37:54 signalk-to-influxdb:Error: node-influx expected the results length to equal 1, but it was 0. Please report this here: https://git.io/influx-err
May 02 21:37:54 Error: node-influx expected the results length to equal 1, but it was 0. Please report this here: https://git.io/influx-err at Object.parseSingle (/home/pi/.signalk/node_modules/influx/lib/src/results.js:128:15) at /home/pi/.signalk/node_modules/influx/lib/src/index.js:303:38 at runMicrotasks (<anonymous>) at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by tkurki** [comment]
I don’t use telegraf so can’t really offer any advice here.

**Comment by macr023** [comment]
This used to work with my previous install of openplotter, is there a way to downgrade signalk-to-influxdb plugin ?

**Comment by tkurki** [comment]
In $HOME/.signalk `npm install —save signalk-to-influxdb@version` but I very much doubt that is the issue. See https://www.npmjs.com/package/signalk-to-influxdb?activeTab=versions

**Comment by macr023** [comment]
Thanks, I have instead redirected signalk-to-influxdb to the local influxdb on the pi, and from there I setup a subscription to output to the local telegraf which then can buffer data for days if need be and telegraf will forward to my home instance via VPN. The point is to keep local on boat  for 30 days and at home unlimited. But since the connection to home is on and off I need a buffering system. I recall in my previous install using telgraf that replicated data stream to local influx and remote influx. Either way this works. Thanks!

**Comment by Ahmed7339** [comment]
Telegram hesabıma giriş yapamıyorum, çıkış yaptım ve çip hasar görmüş, hesabıma tekrar nasıl giriş yapabilirim?
