### ISSUE TITLE
Venus OS - signal k to influxdb2

### ISSUE THREAD

**Issue by dahlei** [tkurki/signalk-to-influxdb#69]
I have Venus OS with the signal k to influxdb 2. I have created bucket and api tokes, but no data is getting through?

Server log:
Oct 21 17:45:52 x [RequestTimedOutError]: Request timed out at ClientRequest.<anonymous> (/data/conf/signalk/node_modules/@influxdata/influxdb-client/dist/index.js:5:6447) at ClientRequest.emit (node:events:517:28) at Socket.emitRequestTimeout (node:_http_client:847:9) at Object.onceWrapper (node:events:631:28) at Socket.emit (node:events:529:35) at Socket._onTimeout (node:net:598:8) at listOnTimeout (node:internal/timers:569:17) at process.processTimers (node:internal/timers:512:7)

**Comment by tkurki** [comment]
Your url is probably wrong, the plugin’s write requests are timing out.

**Comment by dahlei** [comment]
Yes that maybe, what should it be?
http://localhost:8086
http://venus.local:3000
http://venus.local:8086

**Comment by dahlei** [comment]
With http://venus.local:8086 I get different error in server log:

Oct 22 09:19:19 Error: connect ECONNREFUSED 192.168.81.116:8086 at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) { errno: -111, code: 'ECONNREFUSED', syscall: 'connect', address: '192.168.81.116', port: 8086 }

**Comment by dahlei** [comment]
With http://venus.local:3000 I get this message:

Oct 22 09:56:17 m [HttpError]: 404 Not Found : <!DOCTYPE html> <html lang="en"> <head> <meta charset="utf-8"> <title>Error</title> </head> <body> <pre>Cannot GET /api/v2/orgs</pre> </body> </html> at IncomingMessage.<anonymous> (/data/conf/signalk/node_modules/@influxdata/influxdb-client/dist/index.js:5:5671) at IncomingMessage.emit (node:events:529:35) at endReadableNT (node:internal/streams/readable:1368:12) at process.processTicksAndRejections (node:internal/process/task_queues:82:21) { statusCode: 404, statusMessage: 'Not Found', body: '<!DOCTYPE html>\n' + '<html lang="en">\n' + '<head>\n' + '<meta charset="utf-8">\n' + '<title>Error</title>\n' + '</head>\n' + '<body>\n' + '<pre>Cannot GET /api/v2/orgs</pre>\n' + '</body>\n' + '</html>\n', contentType: 'text/html; charset=utf-8', _retryAfter: 0 }

**Comment by dahlei** [comment]
I only have the "signalk - to influxdb2" plugin running on Venus OS, the influxdb online has this url: https://eu-central-1-1.aws.cloud2.influxdata.com/

Tried entering this as the url with no luck.

Is this even possible?
